[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mcp-function-demo"
version = "0.0.1"
description = "MCP Function Demo"
readme = {text = "", content-type = "text/plain"}
authors = [
    {name = "Idea Bosque", email = "ideabosque@gmail.com"}
]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.setuptools]
packages = ["mcp_function_demo"]
include-package-data = true
